#! /bin/sh

export PS4="$ORDERLY_SERVICE_NAME-$ORDERLY_ACTION+ "

set -eux

case $ORDERLY_ACTION in
  RUN)
    exec redis-server
  ;;
  WAIT_STARTED)
    for i in $(seq 10)
    do
      sleep 0.1
      if redis-cli ping | grep PONG
      then
        exit 0
      fi
    done
    echo "start failed"
    exit 1
  ;;
  CHECK)
    if ! redis-cli ping | grep PONG
    then
      exit 1
    fi
  ;;
  SHUTDOWN)
    echo "shutting down redis pid=($ORDERLY_PID)"
    redis-cli shutdown || kill -9 $ORDERLY_PID
  ;;
  CLEANUP)
    rm -f dump.rdb
  ;;
  *)
    echo "unknown action: $ORDERLY_ACTION"
    exit 1
  ;;
esac
