#! /bin/sh

export PS4="$ORDERLY_SERVICE_NAME-$ORDERLY_ACTION+ "

set -eux

case $ORDERLY_ACTION in
  RUN)
    while true
    do
      case $(shuf -i 1-20 -n 1) in
      1) redis-cli shutdown || true ;;
      2) echo "crash! doh!" ; exit 1 ;;
      *) redis-cli ping || true ; sleep 1 ;;
      esac
    done
  ;;
  WAIT_STARTED)
    echo "starting slowly..."
    sleep 5
    echo "done!"
  ;;
  CHECK)
    true
  ;;
  SHUTDOWN)
    kill -9 $ORDERLY_PID
  ;;
  CLEANUP)
    true
  ;;
  *)
    echo "unknown action: $ORDERLY_ACTION"
    exit 1
  ;;
esac
