#! /usr/bin/env bash

set -eu

p () {
  echo "$ORDERLY_SERVICE_NAME $ORDERLY_ACTION"
}

case $ORDERLY_ACTION in
  RUN)
    p
    sleep 1
    echo "sv SIGNAL_PARENT"
    kill -SIGTERM $ORDERLY_SUPERVISOR_PID
  ;;
  WAIT_STARTED)
    sleep 0.1
    p
  ;;
  CHECK)
    true # not interested in check this test.
  ;;
  SHUTDOWN)
    kill -9 $ORDERLY_RUN_PID
    p
  ;;
  CLEANUP)
    p
  ;;
  *)
    echo "unknown action: $ORDERLY_ACTION"
    exit 1
  ;;
esac
