#! /usr/bin/env bash


dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$dir"

set -eu

if timeout 30s orderly -max-restart-tokens 2 -restart-tokens-per-second 0 -all-commands ./lifecycle -- \
  -name sv -all-commands ./sv > test.out
then
  echo "expected an error."
  exit 1
fi

diff -u <(grep -e "^sv" -e "^lifecycle" test.out) test.expected
