#! /usr/bin/env bash

set -eu

p () {
  echo "$ORDERLY_SERVICE_NAME $ORDERLY_ACTION"
}

case $ORDERLY_ACTION in
  RUN)
    p
    exec sleep 9999
  ;;
  WAIT_STARTED)
    sleep 0.1
    p
  ;;
  CHECK)
    p
  ;;
  SHUTDOWN)
    p
    if test "${SHUTDOWN_NOOP:-no}" = "yes"
    then
      echo "sv SHUTDOWN NOOP"
      exit 0 # skip timeout below, but do nothing so we should still timeout.
    else
      kill -9 $ORDERLY_PID
    fi
  ;;
  CLEANUP)
    p
  ;;
  *)
    echo "unknown action: $ORDERLY_ACTION"
    exit 1
  ;;
esac

if test "$ORDERLY_ACTION" = "$TIMEOUT_ACTION"
then
  sleep 99999
fi
